### ISSUE TITLE
Surprising response data

### ISSUE THREAD

**Issue by MartinKavik** [trevorblades/countries#17]
Just some ideas for future improvements. See code with comments below.

---

Input A:
```graphql
query CountryA {
  country(code: "NO") {
    languages {
      code
      name
      native
      rtl
    }
  }
}
```
Output A:
```js
{
  "data": {
    "country": {
      "languages": [
         ...
        {
          "code": "nb",
          "name": null,    // missing data in data-source?
          "native": null,   // missing data in data-source?
          "rtl": false
        },
        ...
      ]
    }
  }
}
```

---

Input B:
```graphql
query CountryB {
  country(code: "AQ") {
    capital
    currency
  }
}
```
Output B:
```js
{
  "data": {
    "country": {
      "capital": "",   // should be nullable?
      "currency": ""  // should be nullable?
    }
  }
}
```

**Comment by trevorblades** [comment]
Thanks for pointing this out @MartinKavik! I've made a couple of commits to address these points:

- 5f5a3535feb27184b5c84a7b9eb1f17de5d196dc makes `capital` and `currency` nullable
- c78571d1306de08e0a983b3a6efcc7dcac1daff7 updates the `countries-list` dependency so we get the previously missing data for language at code `nb`

Here's a screenshot of a query that tests these changes:

![Screen Shot 2020-03-27 at 1 47 57 PM](https://user-images.githubusercontent.com/1216917/77799430-04d58800-7032-11ea-9e7b-b3a6663dd37c.png)
