### ISSUE TITLE
How to render the emojiU on react component?

### ISSUE THREAD

**Issue by SteplerPaulo** [trevorblades/countries#37]
How to render the country emojiU on react component?

**Comment by trevorblades** [comment]
In a React component, you'd probably want to use the `emoji` field instead of `emojiU`. Any reason why you need to use `emojiU`?

**Comment by weitzz** [comment]
I have the same problem but it would be to render the emoji

**Comment by trevorblades** [comment]
You should be able to render the emoji in React the same as you would any string.

```jsx
<div>{country.emoji}</div>
```

**Comment by weitzz** [comment]
that's how I'm doing and it just comes back like this:
![countries](https://user-images.githubusercontent.com/52081179/144299971-3409aa7a-71a9-4db2-986e-9e144c989334.png)

**Comment by trevorblades** [comment]
What OS and browser are you using? Some fonts, like Microsoft's default font, Segoe UI don't support flag emojis. More info in this stackoverflow post: https://stackoverflow.com/a/54520964

**Comment by weitzz** [comment]
I'm using Windows and Chrome as my browser.
I did a test with mozila and it worked
