### ISSUE TITLE
Proposition: add static documentation

### ISSUE THREAD

**Issue by pelletier197** [trevorblades/countries#45]
Hello! I am the maintainer of a documentation tool called [Magidoc](https://github.com/magidoc-org/magidoc), a tool that generates static GraphQL API documentation references. 

I would like to propose to integrate Magidoc into your great project to build a static API reference. This would allow users to easily get an overview of the whole API, but also other documentation that may be useful to use your API. You could even move all your examples or any other content you want there, since Magidoc supports `Custom pages`.

If you want to see an example, here is a link to a [demo website](https://magidoc-carbon-multi-page.netlify.app/welcome).

I am also willing to help you integrate it if you want, and this could be hosted on any static content host: so can be GitHub pages, Netlify, Vercel, or anything else you want.

Let me know what you think about the idea, and feel free to close the issue if you're not interested.

**Comment by trevorblades** [comment]
Hey! That sounds cool. Do you want to open a PR that sets up Magidoc? I suspect that we'll have to add descriptions to the fields in the schema to make the site work best. I don't mind doing that part.

**Comment by pelletier197** [comment]
> I suspect that we'll have to add descriptions to the fields in the schema to make the site work best.

That is not 100% necessary, but as you might suspect, documentation will be very plain if there is not comment on the schema.

> Do you want to open a PR that sets up Magidoc?

Yeah absolutely, I'll be happy to do that when I get some time (hopefully by the end of the week). The only thing I'd need from you is to enable GitHub pages on the repo once this is merged.

**Comment by pelletier197** [comment]
@trevorblades the GitHub action seems to have passed correctly (see [branch gh-pages](https://github.com/trevorblades/countries/tree/gh-pages)). 

However, I believe GitHub pages may not be activated in your repo settings. This would explain why https://trevorblades.github.io/countries is not accessible.

**Comment by trevorblades** [comment]
Hooray, it's fixed! Thanks so much for your help in setting this up @pelletier197 🤗

**Comment by pelletier197** [comment]
My pleasure. Enjoy, and let me know if something could be improved in Magidoc 🙂
