### ISSUE TITLE
Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by Pannekake** [trevorblades/countries#55]
Query:
`{
  countries(filter: {code: {eq: "US"}}) {
    states {
      name
      value: code
    }
  }
}`

Response:
`{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'toString')",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "countries"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "TypeError: Cannot read properties of undefined (reading 'toString')",
          "    at isVanillaObject (/var/task/netlify/functions/graphql/graphql.js:50619:107)",
          "    at createQueryOperations (/var/task/netlify/functions/graphql/graphql.js:50864:14)",
          "    at createQueryOperation (/var/task/netlify/functions/graphql/graphql.js:50850:18)",
          "    at createDefaultQueryOperation (/var/task/netlify/functions/graphql/graphql.js:51293:16)",
          "    at createDefaultQueryTester (/var/task/netlify/functions/graphql/graphql.js:51302:18)",
          "    at resolve (/var/task/netlify/functions/graphql/graphql.js:58100:42)",
          "    at field.resolve (/var/task/netlify/functions/graphql/graphql.js:54949:22)",
          "    at executeField (/var/task/netlify/functions/graphql/graphql.js:8987:24)",
          "    at executeFields (/var/task/netlify/functions/graphql/graphql.js:8962:24)",
          "    at executeOperation (/var/task/netlify/functions/graphql/graphql.js:8933:18)"
        ]
      }
    }
  ],
  "data": null
}`

**Comment by trevorblades** [comment]
For reference: https://github.com/trevorblades/countries/pull/54#issuecomment-1478229295

**Comment by Pannekake** [comment]
Yes! @trevorblades it seems to have done the trick! I am using Hasura`s remote schemas 👍

**Comment by trevorblades** [comment]
That's great to hear! Just wanted to confirm that this issue is address _as well as_ the issue with remote schemas?

**Comment by trevorblades** [comment]
That's great to hear! Happy querying :)

**Comment by DanRymo** [comment]
Fantastic response time, thank you @trevorblades! ❤️
