### ISSUE TITLE
Query Returning null?

### ISSUE THREAD

**Issue by AbbyNyakara** [trevorblades/countries#59]
I'm trying to filter the countries by continent. i.e List the countries as per the continent. I am getting a null and it does'nt make much sense why its not working: 

This is my query: 

`query {
  countries(filter: {continent: {eq: "Africa"}}){
    name,
    capital
  }
}`

**Comment by trevorblades** [comment]
Ah, the `continent` filter expects a continent code, like "AF" in this case. Another way to make this query would be querying for Africa using the `continent(code: "AF")` field and then selecting the `countries` subfield:

```graphql
query ListCountriesInAfrica {
  countries(filter: {continent: {eq: "AF"}}) {
    name
    capital
  }
}

query GetAfricaAndListCountries {
	continent(code: "AF") {
    countries {
      name
      capital
    }
  }
}
```

**Comment by trevorblades** [comment]
That's a great point. I've updated the readme [here](https://github.com/trevorblades/countries#filtering) to add a note about this detail.
