### ISSUE TITLE
Issue with the 'name' Field in GraphQL Playground and the Need for README Update"

### ISSUE THREAD

**Issue by can101** [trevorblades/countries#67]
I am encountering an issue in GraphQL Playground despite the query being shown as an example in the README file. It seems like the name field has been removed from the filter parameters, so it may require an update to the README file. Below, I'm providing the error message along with the query:

GraphQL Query:

```gql
query ListCountriesThatBeginWithTheLetterA {
  countries(filter: { name: { regex: "^A" } }) {
    code
    name
    currency
  }
}
```
Error Message:

```shell
{
  "errors": [
    {
      "message": "Field \"name\" is not defined by type \"CountryFilterInput\".",
      "locations": [
        {
          "line": 2,
          "column": 22
        }
      ]
    }
  ]
}
```

the README.md  [link](https://github.com/trevorblades/countries/blob/main/README.md)
the playground  [link](https://countries.trevorblades.com/)

**Comment by trevorblades** [comment]
Good catch! I just [updated the API](b11d0f785dbde5f066875c2807268d89c53451e2) to account for this. If you try running that query in the playground again, it should work now. Thanks for pointing this out!

**Comment by can101** [comment]
Thanks for the issue update, it's working now.
